### ISSUE TITLE
DOC: Relationship to black

### ISSUE THREAD

**Issue by MartinThoma** [Intsights/flake8-intsights#6]
The [black autoformatter](https://github.com/psf/black) is pretty popular and also opinionated. What is the relationship between flake8-intsights and black?

(Side questions: why "intsights"? should it be "insights" and was a typo?)

**Comment by wavenator** [comment]
Hi Martin!

First, thanks for your interest in our Flake8 plugin.
Intsights is the name of our company, which is a cybersecurity company based in Israel/USA.
In the past, we've evaluated `black` internally and found it unsuitable for our needs. Our linter follows guidelines which we find a better fit for our standards. We've also tried to customize `black` and `yapf` without success. In the Readme you can find all our guidelines which we follow.
If you find any particular direction as problematic, misleading, irrelevant, feel free to open an issue so we can discuss it and come to a conclusion.

Thanks a lot again!

**Comment by MartinThoma** [comment]
Thank you for the answer, @wavenator :hugs:
